name: 'Run tests on creating a pull request'

on:
  pull_request:
    branches: 
      - 'main'

jobs:
  test-pr:
    name: 'Run unit and E2E tests'
    runs-on: ubuntu-latest

    steps: 
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./effectly/package.json
      - name: 'Run unit tests'
        run: cd effectly && yarn test:unit
      - name: 'Run end-to-end tests'
        run: cd effectly && yarn cypress:run